### ISSUE TITLE
Not working on HA 0.93

### ISSUE THREAD

**Issue by rhannink** [yniezink/twentemilieu#2]
Hallo,
Tried it this morning, first I made a **manifest.json** and an empty **__init__.py** file in the **custom_components/twentemilieu** directory. This is because since 0.92 HA Works with integrations.

When I then restart HA, it does not start anymore, I see no errors in the log.

In the **Configuration.yaml** I added:

```
sensor:
  - platform: twentemilieu
    postcode: XXXXAA
    huisnummer: 38
    resources:
      - GREEN
      - PACKAGES
      - PAPER
      - GREY
```
